//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Data.BDSSO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaCatView
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JFMGigyaCatView()
        {
            this.JFMGigyaCtrlPlugIns = new HashSet<JFMGigyaCtrlPlugIn>();
        }
    
        public int IdTipoIn { get; set; }
        public string DescriptionVc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaCtrlPlugIn> JFMGigyaCtrlPlugIns { get; set; }
    }
}
