//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Data.BDSSO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaCtrlCss
    {
        public int IdIn { get; set; }
        public string NameVc { get; set; }
        public string DescriptionVc { get; set; }
        public int OrdIn { get; set; }
        public string SiteApiKeyVc { get; set; }
        public System.DateTime LastUpdateDt { get; set; }
        public string PathVc { get; set; }
    
        public virtual JFMGigyaSite JFMGigyaSite { get; set; }
    }
}
