//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Data.BDSSO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JFMGigyaSite()
        {
            this.JFMGigyaCtrlCsses = new HashSet<JFMGigyaCtrlCss>();
            this.JFMGigyaCtrlPlugIns = new HashSet<JFMGigyaCtrlPlugIn>();
            this.JFMGigyaCtrlScripts = new HashSet<JFMGigyaCtrlScript>();
            this.JFMGigyaKeys = new HashSet<JFMGigyaKey>();
            this.JFMGigyaSiteReCAPTCHAs = new HashSet<JFMGigyaSiteReCAPTCHA>();
            this.JFMGigyaSiteUrls = new HashSet<JFMGigyaSiteUrl>();
        }
    
        public string ApiKeyVc { get; set; }
        public string DomainVc { get; set; }
        public string DescriptionVc { get; set; }
        public string UserKeyVc { get; set; }
        public string UserSecretKeyVc { get; set; }
        public int ExpirationKeyInMinsIn { get; set; }
        public int ExpirationSessionInMinsIn { get; set; }
        public string FolderMediaVc { get; set; }
        public System.Guid Partner_idGd { get; set; }
        public int ServiceId { get; set; }
        public bool IsActivatedBl { get; set; }
        public bool EnableReCAPTCHABl { get; set; }
        public System.DateTime RegistrationDt { get; set; }
        public System.DateTime LastUpdateDt { get; set; }
        public string ConfigFileVc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaCtrlCss> JFMGigyaCtrlCsses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaCtrlPlugIn> JFMGigyaCtrlPlugIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaCtrlScript> JFMGigyaCtrlScripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaKey> JFMGigyaKeys { get; set; }
        public virtual JFMGigyaService JFMGigyaService { get; set; }
        public virtual JFMGigyaSitePartner JFMGigyaSitePartner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaSiteReCAPTCHA> JFMGigyaSiteReCAPTCHAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaSiteUrl> JFMGigyaSiteUrls { get; set; }
    }
}
