//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Data.BDSSO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaCtrlPlugIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JFMGigyaCtrlPlugIn()
        {
            this.JFMGigyaCtrlImages = new HashSet<JFMGigyaCtrlImage>();
        }
    
        public int IdViewIn { get; set; }
        public string HTMLVc { get; set; }
        public string DescriptionVc { get; set; }
        public string PathVc { get; set; }
        public int CatViewIdTipoIn { get; set; }
        public string SiteApiKeyVc { get; set; }
        public System.DateTime LastUpdateDt { get; set; }
    
        public virtual JFMGigyaCatView JFMGigyaCatView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaCtrlImage> JFMGigyaCtrlImages { get; set; }
        public virtual JFMGigyaSite JFMGigyaSite { get; set; }
    }
}
