//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Business.www.kcmsso.com_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaSiteUrl
    {
        public int IdIn { get; set; }
        public string UrlVc { get; set; }
        public string DescriptionVc { get; set; }
        public string SiteApiKeyVc { get; set; }
    
        public virtual JFMGigyaSite JFMGigyaSite { get; set; }
    }
}
