//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Business.www.kcmsso.com_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JFMGigyaEntities : DbContext
    {
        public JFMGigyaEntities()
            : base("name=JFMGigyaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JFMGigyaCatView> JFMGigyaCatViews { get; set; }
        public virtual DbSet<JFMGigyaCtrlCss> JFMGigyaCtrlCsses { get; set; }
        public virtual DbSet<JFMGigyaCtrlImage> JFMGigyaCtrlImages { get; set; }
        public virtual DbSet<JFMGigyaCtrlPlugIn> JFMGigyaCtrlPlugIns { get; set; }
        public virtual DbSet<JFMGigyaCtrlScript> JFMGigyaCtrlScripts { get; set; }
        public virtual DbSet<JFMGigyaKey> JFMGigyaKeys { get; set; }
        public virtual DbSet<JFMGigyaService> JFMGigyaServices { get; set; }
        public virtual DbSet<JFMGigyaSite> JFMGigyaSites { get; set; }
        public virtual DbSet<JFMGigyaSitePartner> JFMGigyaSitePartners { get; set; }
        public virtual DbSet<JFMGigyaSiteReCAPTCHA> JFMGigyaSiteReCAPTCHAs { get; set; }
        public virtual DbSet<JFMGigyaSiteUrl> JFMGigyaSiteUrls { get; set; }
    }
}
