//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Business.www.kcmsso.com_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaKey
    {
        public string HexKeyVc { get; set; }
        public string RandomKeyVc { get; set; }
        public string SessionVc { get; set; }
        public bool IsResetPasswordBl { get; set; }
        public string SiteApiKeyVc { get; set; }
        public System.DateTime RegistrationDt { get; set; }
    
        public virtual JFMGigyaSite JFMGigyaSite { get; set; }
    }
}
