//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCM.ServiciosInternet.Plugins.Business.www.kcmsso.com_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class JFMGigyaService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JFMGigyaService()
        {
            this.JFMGigyaSites = new HashSet<JFMGigyaSite>();
        }
    
        public int IdIn { get; set; }
        public string NameVc { get; set; }
        public string UrlServiceVc { get; set; }
        public string PathServiceVc { get; set; }
        public string ServiceNameVc { get; set; }
        public string ResetFormVc { get; set; }
        public string AfterLoginFormVc { get; set; }
        public System.DateTime StartDt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JFMGigyaSite> JFMGigyaSites { get; set; }
    }
}
